### PR TITLE
support nested collections (issue #5)

### PR DESCRIPTION
**Pull request by sojournerc**
This was a quick and dirty implementation, and could probably use a little refactor for readability. 

Took the recursive approach, just had to break apart the methods to be able to recurse the right step in the process.

### CODE REVIEW

**Comment by sojournerc** [comment]
resolves #5

**Comment by Ajaxy** [comment]
@sojournerc Thanks for the PR! Looks good to me. However, wouldn't be easier just to count `[]`-s at the end and return some kind of `collectionDimension` from the `parseType` function? Then we can do just:
```js
  if (isCollection) {
    for (let i = 0; i < collectionDimension - 1; i++) {
      def = {
        type: 'array',
        items: def,
      };
    }
  }
```

**Comment by sojournerc** [comment]
@Ajaxy thanks for the feedback. 

I've been playing with that approach and it has some limitations:
- The nested ref doesn't get validated (b/c the nested property doesn't get passed through `parseSingleProp` as it does with the recursive approach. 
- For the same reason the nested ref also doesn't get processed correctly into the swagger format

I could do some surgery on `parseSingleProp` to make those possible for every dimension, but I'm not sure it'd be any clearer/better than the current approach.

Thoughts?

**Comment by Ajaxy** [comment]
@sojournerc Not sure what you mean by "doesn't get validated". Here is a draft of how I see it may be done, your tests pass: https://github.com/Ajaxy/tinyspec/pull/10/files

**Comment by sojournerc** [comment]
Ha, that is much easier and cleaner. I got stuck in the idea of recursion, and didn't think to pull all the brackets off the type def. 

Anyway, thanks again. I'll close this PR since your's is better and ready.

**Pull request closed without merging**
