### PR TITLE
Add support for "date" type

### LINKED ISSUE #3: Support for "date" type
OpenAPI supports the `date` format for the `string` type, but tinyspec doesn't have a corresponding type. It would be great to have it. (I would even go as far as redefining the `d` shorthand type to the new `date` type, and defining the new `dt` shorthand for the existing `datetime` type.)

P. S. I'm very new to the world of REST API specifications, but tinyspec already looks like a useful "source" language for OpenAPI, an attractive alternative to just writing these verbose specifications by hand.

### PR DESCRIPTION
**Pull request by pvgoran**
Resolves #3.

### CODE REVIEW

**Comment by Ajaxy** [comment]
Thanks for the PR. Could you please make sure that tests are passing? I believe you also need to edit `tests/models/expectations/primitiveTypes.definitions.json`.

**Comment by pvgoran** [comment]
Done. (I force-pushed a new commit.)

**Comment by Ajaxy** [comment]
Cool!

Could you please also add `date` example to the second model in the same file (testing _Edge case: prop names like types or type symbols_)?

Also, would be great if you add your example to the first model at the end (not in the middle) as `r: date`. Otherwise, the diff looks a bit messed up. 

I connected the CI checks to run tests on PRs, but for some reason it's not attached to the exising PR. Would you mind creating a new one?

**Comment by pvgoran** [comment]
Will do.

> Also, would be great if you add your example to the first model at the end (not in the middle) as r: date. Otherwise, the diff looks a bit messed up.

The idea was to follow the logical structure, I considered prettiness of diffs as a secondary concern. But I don't mind doing it the other way.

**Comment by Ajaxy** [comment]
Moved to #9

**Pull request closed without merging**
